const foods = [
  {
    id: 32,
    title: "Cheese Beef Hamburger",
    desc: "fried chicken balls, french fries !",
    price: 5.39,
    img: "./../public/images/best Seller/Cheese Beef Hamburger.png",
    category: "bestSeller",
    badge: "./../public/images/Badge Discount.png",
  },
  {
    id: 33,
    title: "Combo funny",
    desc: "fried chicken balls, french fries !",
    price: 10.39,
    img: "./../public/images/best Seller/Combo funny.png",
    category: "bestSeller",
    badge: "./../public/images/Badge Discount.png",
  },
  {
    id: 34,
    title: "‌Chicken with Spicy Sauce",
    desc: "chili garlic sauce, black pepper sauce !",
    price: 7.39,
    img: "./../public/images/best Seller/‌Chicken with Spicy Sauce.png",
    category: "bestSeller",
    badge: "./../public/images/Badge Discount.png",
  },
  {
    id: 35,
    title: "Salad mixed vinegar",
    desc: "Salad, vinegar, tomato !",
    price: 3.39,
    img: "./../public/images/best Seller/Salad mixed vinegar.png",
    category: "bestSeller",
    badge: "./../public/images/Badge Discount.png",
  },
  {
    id: 36,
    title: "Chicken burger",
    desc: "fried chicken!",
    price: 5.39,
    img: "./../public/images/best Seller/Chicken burger.png",
    category: "bestSeller",
    badge: "./../public/images/Badge Discount.png",
  },
  {
    id: 37,
    title: "Lipton",
    desc: "Tea with Ice,Lime and Mint !",
    price: 0.89,
    img: "./../public/images/best Seller/Lipton.png",
    category: "bestSeller",
    badge: "./../public/images/Badge Discount.png",
  },
  {
    id: 7,
    title: "2 pieces",
    desc: "2 pieces spicy with salad,bread & sauce",
    price: 7.99,
    img: "./../public/images/chicken/2teke-tond.jpg",
    category: "chicken",
  },
  {
    id: 8,
    title: "2 pieces",
    desc: "2 pieces normal with salad,bread & sauce",
    price: 7.59,
    img: "./../public/images/chicken/2teke.jpg",
    category: "chicken",
  },
  {
    id: 9,
    title: "3 pieces",
    desc: "3 pieces normal with salad,bread & sauce",
    price: 9.99,
    img: "./../public/images/chicken/3teke.jpg",
    category: "chicken",
  },
  {
    id: 10,
    title: "3 pieces",
    desc: "3 pieces spicy with salad,bread & sauce",
    price: 10.59,
    img: "./../public/images/chicken/3teke-tond.jpg",
    category: "chicken",
  },
  {
    id: 11,
    title: "Shrimps",
    desc: "Fried Shrimps with salad,bread & sauce",
    price: 15.99,
    img: "./../public/images/chicken/meigoo.jpg",
    category: "chicken",
  },
  {
    id: 12,
    title: "strips",
    desc: "5 pieces strips with salad,bread & sauce",
    price: 10.99,
    img: "./../public/images/chicken/5teke-feele.jpg",
    category: "chicken",
  },
  {
    id: 13,
    title: "Margerita",
    desc: "tomato , cheese , basil",
    price: 5.99,
    img: "./../public/images/pizza/margerita.jpg",
    category: "pizza",
  },
  {
    id: 14,
    title: "chicken",
    desc: "tomato , cheese , chicken",
    price: 7.99,
    img: "./../public/images/pizza/morq.jpg",
    category: "pizza",
  },
  {
    id: 15,
    title: "Turkey",
    desc: "tomato , cheese , turkey",
    price: 10.99,
    img: "./../public/images/pizza/boqalamon.jpg",
    category: "pizza",
  },
  {
    id: 16,
    title: "Pepperoni",
    desc: "tomato , cheese , pepperoni",
    price: 7.99,
    img: "./../public/images/pizza/peperoni.jpg",
    category: "pizza",
  },
  {
    id: 17,
    title: "Mushroom",
    desc: "tomato , cheese , mushroom",
    price: 6.99,
    img: "./../public/images/pizza/qarch.jpg",
    category: "pizza",
  },
  {
    id: 18,
    title: "Steak",
    desc: "tomato , cheese , Steak . black Olive",
    price: 13.99,
    img: "./../public/images/pizza/stake.jpg",
    category: "pizza",
  },
  {
    id: 19,
    title: "Bacon Burger",
    desc: "bread , onion , tomato , cheese , bacon , burger !",
    price: 4.99,
    img: "./../public/images/burger/bacon-burger.jpg",
    category: "burger",
  },
  {
    id: 20,
    title: "Big Burger",
    desc: "bread , onion , tomato , cheese , mushroom ,two big burger !",
    price: 7.59,
    img: "./../public/images/burger/big-burger.jpg",
    category: "burger",
  },
  {
    id: 21,
    title: "Burger",
    desc: "bread , onion , tomato , burger !",
    price: 3.99,
    img: "./../public/images/burger/burger.jpg",
    category: "burger",
  },
  {
    id: 22,
    title: "Cheese Burger",
    desc: "bread , onion , tomato , cheese , burger !",
    price: 4.39,
    img: "./../public/images/burger/cheese-burger.jpg",
    category: "burger",
  },
  {
    id: 23,
    title: "Double Burger",
    desc: "bread , onion , tomato , cheese , two burger !",
    price: 5.99,
    img: "./../public/images/burger/double-burger.jpg",
    category: "burger",
  },
  {
    id: 24,
    title: "Vegi Burger",
    desc: "bread , onion , tomato , cheese ,vegan burger !",
    price: 4.99,
    img: "./../public/images/burger/veg-burger.jpg",
    category: "burger",
  },
  {
    id: 25,
    title: "Brosteka",
    desc: "brosteka !",
    price: 4.99,
    img: "./../public/images/dessert/brosteka.jpg",
    category: "dessert",
  },
  {
    id: 26,
    title: "Espinach Salad",
    desc: "Espinach !",
    price: 4.99,
    img: "./../public/images/dessert/esfenaj.jpg",
    category: "dessert",
  },
  {
    id: 27,
    title: "French Fries",
    desc: "french-fries !",
    price: 4.99,
    img: "./../public/images/dessert/french-fries.jpg",
    category: "dessert",
  },
  {
    id: 28,
    title: "Pine Salad",
    desc: "pine seed  !",
    price: 4.99,
    img: "./../public/images/dessert/kaj.jpg",
    category: "dessert",
  },
  {
    id: 29,
    title: "Garlic Bread",
    desc: "bread with garlic flavor !",
    price: 4.99,
    img: "./../public/images/dessert/nan-sir.jpg",
    category: "dessert",
  },
  {
    id: 30,
    title: "Poatato Soup",
    desc: "poatato-soup !",
    price: 4.99,
    img: "./../public/images/dessert/poatato-soup.jpg",
    category: "dessert",
  },
  {
    id: 31,
    title: "Cesar",
    desc: "cesar salad with chicken !",
    price: 4.99,
    img: "./../public/images/dessert/sezar.jpg",
    category: "dessert",
  },

  {
    id: 1,
    title: "Coca",
    desc: "Coca Cola drink",
    price: 1,
    img: "./../public/images/drink/coca.jpg",
    category: "drink",
  },
  {
    id: 2,
    title: "Fanta",
    desc: "fanta drink",
    price: 1,
    img: "./../public/images/drink/fanta.jpg",
    category: "drink",
  },
  {
    id: 3,
    title: "Water",
    desc: "water drink",
    price: 1,
    img: "./../public/images/drink/water.jpg",
    category: "drink",
  },
  {
    id: 4,
    title: "Sprite",
    desc: "Sprite drink",
    price: 0.89,
    img: "./../public/images/drink/sprite.jpg",
    category: "drink",
  },
  {
    id: 5,
    title: "Zero Coca",
    desc: "Coca with no suger drink",
    price: 1,
    img: "./../public/images/drink/zero.jpg",
    category: "drink",
  },
  {
    id: 6,
    title: "beer",
    desc: "soft beer drink",
    price: 1.69,
    img: "./../public/images/drink/beer.jpg",
    category: "drink",
  },
];

export { foods };
